name: 'Goose Code Action'
description: 'AI-powered code automation with Goose – live progress + PR link'
inputs:
  instructions:
    description: 'Prompt/instructions for Goose (e.g., from comment)'
    required: false
  goose_args:
    description: 'Additional CLI args for Goose (e.g., --max-turns 5)'
    required: false
  openai_api_key:
    description: 'OpenAI-compatible API key'
    required: true
  openai_host:
    description: 'OpenAI-compatible host (optional)'
    required: false
  openai_model:
    description: 'Model name (e.g., gpt-4o, Qwen3-…)'
    required: true
  github_token:
    description: 'GitHub token (needs repo, issues, pull-requests)'
    required: true
  trigger_phrase:
    description: 'Mention trigger (default: @goose)'
    required: false
    default: '@goose'
runs:
  using: 'composite'
  steps:

    # -------------------------------------------------
    # 1. Checkout + gather event data (safe for any chars)
    # -------------------------------------------------
    - name: Checkout repo
      uses: actions/checkout@v4
      with: { fetch-depth: 0 }

    - name: Gather Event Info
      if: github.event_name == 'pull_request' || github.event_name == 'issue_comment'
      shell: bash
      run: |
        if [ "${{ github.event_name }}" = "issue_comment" ] && cat <<'EOF' | grep -q "${{ inputs.trigger_phrase }}"
        ${{ github.event.comment.body }}
        EOF
        then
          INSTRUCTIONS=$(cat <<'EOF' | sed "s/${{ inputs.trigger_phrase }} *//"
        ${{ github.event.comment.body }}
        EOF
          )
          ISSUE_NUMBER=${{ github.event.issue.number }}
        elif [ "${{ github.event_name }}" = "pull_request" ]; then
          ISSUE_NUMBER=${{ github.event.pull_request.number }}
          { echo "# Files Changed"
            gh pr view $ISSUE_NUMBER --json files -q '.files[] | "* " + .path + " (" + (.additions|tostring) + " additions, " + (.deletions|tostring) + " deletions)"'
            echo; echo "# Changes Summary"
            gh pr diff $ISSUE_NUMBER
          } > changes.txt
          INSTRUCTIONS="Summarize and review the following changes:\n$(cat changes.txt)"
        else
          INSTRUCTIONS="${{ inputs.instructions }}"
          ISSUE_NUMBER=${{ github.event.issue.number }}
        fi
        echo "INSTRUCTIONS=$INSTRUCTIONS" >> $GITHUB_ENV
        echo "ISSUE_NUMBER=$ISSUE_NUMBER" >> $GITHUB_ENV
        echo "BASE_BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV

    # -------------------------------------------------
    # 2. Install Goose CLI
    # -------------------------------------------------
    - name: Install Goose CLI
      shell: bash
      run: |
        mkdir -p /home/runner/.local/bin
        curl -fsSL https://github.com/block/goose/releases/download/stable/download_cli.sh \
          | CONFIGURE=false GOOSE_BIN_DIR=/home/runner/.local/bin bash
        echo "/home/runner/.local/bin" >> $GITHUB_PATH

    # -------------------------------------------------
    # 3. Configure Goose
    # -------------------------------------------------
    - name: Configure Goose
      shell: bash
      run: |
        mkdir -p ~/.config/goose
        cat <<EOF > ~/.config/goose/config.yaml
        GOOSE_PROVIDER: openai
        GOOSE_MODEL: ${{ inputs.openai_model }}
        keyring: false
        EOF

    # -------------------------------------------------
    # 4. Git identity
    # -------------------------------------------------
    - name: Setup Git for Commits
      shell: bash
      run: |
        git config --global user.name "Goose Bot"
        git config --global user.email "goose@users.noreply.github.com"

    # -------------------------------------------------
    # 5. Build instructions.txt – forces full Git flow
    # -------------------------------------------------
    - name: Create Instructions File
      shell: bash
      run: |
        # Quote everything that will be used in shell commands
        QUOTED_INSTR=$(printf '%s' "$INSTRUCTIONS" | sed 's/"/\\"/g')
        cat <<'EOF' > instructions.txt
        /mode auto
        /builtin developer
        Execute the task **exactly** as described below using *shell* commands.

        1. Create a new branch:
           ```bash
           git checkout -b goose-task-$(date +%s)
           ```

        2. Make the requested file changes (use `text_editor` when needed).

        3. Stage & commit:
           ```bash
           git add .
           git commit -m "Goose: ${{ env.INSTRUCTIONS }}"
           ```

        4. Push:
           ```bash
           git push origin HEAD
           ```

        5. Create PR:
           ```bash
           gh pr create --title "Goose: ${{ env.INSTRUCTIONS }}" \
                        --body "Automated changes by Goose" \
                        --base ${{ env.BASE_BRANCH }}
           ```

        **User task:** ${{ env.INSTRUCTIONS }}
        EOF

    # -------------------------------------------------
    # 6. Initial progress comment
    # -------------------------------------------------
    - name: Create Initial Progress Comment
      if: env.ISSUE_NUMBER != ''
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        BODY="Goose processing (live log):\n\n(Initializing...)\n\nProgress:\n- [ ] Installing and configuring\n- [ ] Running task\n- [ ] Posting results"
        COMMENT_ID=$(gh api -X POST -F body="$BODY" \
          "repos/${{ github.repository }}/issues/${{ env.ISSUE_NUMBER }}/comments" \
          --jq .id)
        echo "COMMENT_ID=$COMMENT_ID" >> $GITHUB_ENV

    # -------------------------------------------------
    # 7. Configured – first checkbox
    # -------------------------------------------------
    - name: Update Progress – Configured
      if: env.COMMENT_ID != ''
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        BODY="Goose processing (live log):\n\n(Configured Goose & Git...)\n\nProgress:\n- [x] Installing and configuring\n- [ ] Running task\n- [ ] Posting results"
        gh api -X PATCH -F body="$BODY" \
          "repos/${{ github.repository }}/issues/comments/${{ env.COMMENT_ID }}" > /dev/null

    # -------------------------------------------------
    # 8. Run Goose
    # -------------------------------------------------
    - name: Run Goose
      shell: bash
      env:
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
        OPENAI_HOST: ${{ inputs.openai_host }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        goose run --instructions instructions.txt --no-session --with-builtin developer ${{ inputs.goose_args }} \
          | sed -E 's/\x1B\[[0-9;]*[mK]//g' \
          | grep -v "logging to /home/runner/.config/goose/sessions/" \
          | grep -v "^starting session" \
          | grep -v "^Closing session" \
          | sed 's/[[:space:]]*$//' \
          > output.txt

    # -------------------------------------------------
    # 9. Live-looking milestone update
    # -------------------------------------------------
    - name: Update Progress – Task Run (milestones)
      if: env.COMMENT_ID != ''
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        MILESTONES=$(grep -E '───|Great!|Successfully|created the pull request' output.txt \
                     | sed 's/^/  - /')
        BODY="Goose processing (live log):\n\n$MILESTONES\n\n---\n\nProgress:\n- [x] Installing and configuring\n- [x] Running task\n- [ ] Posting results"
        gh api -X PATCH -F body="$BODY" \
          "repos/${{ github.repository }}/issues/comments/${{ env.COMMENT_ID }}" > /dev/null

    # -------------------------------------------------
    # 10. Fallback – only if Goose left unpushed commits
    # -------------------------------------------------
    - name: Fallback Commit & PR
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        git fetch origin
        # Are there commits not on the base branch?
        if [ "$(git rev-list --count HEAD ^origin/${{ env.BASE_BRANCH }})" -gt 0 ]; then
          BRANCH="goose-task-$(date +%s)"
          git checkout -b "$BRANCH" 2>/dev/null || true
          git add . || true
          git commit -m "Goose fallback: ${{ env.INSTRUCTIONS }}" || echo "nothing to commit"
          git push origin "$BRANCH"
          gh pr create --title "Goose fallback: ${{ env.INSTRUCTIONS }}" \
                       --body "Automated fallback after Goose run" \
                       --base ${{ env.BASE_BRANCH }}
        else
          echo "No unpushed commits → skipping fallback"
        fi

    # -------------------------------------------------
    # 11. Final comment – full log + PR link
    # -------------------------------------------------
    - name: Post Final Results
      if: env.ISSUE_NUMBER != ''
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        RESULT=$(cat output.txt)

        # 1. Try to extract PR URL from Goose output
        PR_URL=$(echo "$RESULT" | grep -oE 'https://github\.com/[^/]+/[^/]+/pull/[0-9]+' | head -1)

        # 2. If Goose didn’t print it, ask GitHub for the latest PR from this run
        if [ -z "$PR_URL" ]; then
          PR_URL=$(gh pr list --json url --author "app/github-actions" --limit 1 --jq '.[0].url // empty')
        fi

        if [ -n "$PR_URL" ]; then
          PR_NUM=$(basename "$PR_URL")
          RESULT="${RESULT}\n\n**Linked PR:** [#${PR_NUM}](${PR_URL})"
        fi

        BODY="Goose results:\n\n\`\`\`\n${RESULT}\n\`\`\`\n\nProgress:\n- [x] Installing and configuring\n- [x] Running task\n- [x] Posting results"
        gh api -X PATCH -F body="$BODY" \
          "repos/${{ github.repository }}/issues/comments/${{ env.COMMENT_ID }}" > /dev/null

    # -------------------------------------------------
    # 12. Non-issue events
    # -------------------------------------------------
    - name: Output Results (non-issue)
      if: env.ISSUE_NUMBER == ''
      shell: bash
      run: cat output.txt
